### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by sidkshatriya** [voodoos/merlin-occurrences-switch#1]
Here is the current Makefile

```make
_opam:
	opam switch create . --empty

opam.export: _opam
	opam pin --yes \
	https://github.com/voodoos/ocaml.git#store-shapes-in-summaries+fragments
	opam pin https://github.com/voodoos/dune.git#ocaml-uideps \
	--yes
	opam pin --with-version dev --yes \
	https://github.com/voodoos/ocaml-uideps.git
	opam pin --with-version dev --yes \
	https://github.com/voodoos/merlin.git#project-wide-occurrences
	opam pin --with-version dev --yes \
	https://github.com/voodoos/ocaml-lsp.git#project-wide-occurrences
	opam switch export --freeze  opam.export

switch: _opam
	opam switch import opam.export --switch=.
```

Currently we have 
```
switch: _opam
```

Shouldn't it be something like:
```
switch: opam.export
```

Sorry if I've misunderstood something...

**Comment by voodoos** [comment]
No. You should consider the export file as a "lock" file. The `make opam.export` target will fetch latest version of the branches (which might be broken) and make a new lock file.

The `make switch` target imports a lock file to the current (hopefully empty) switch so that you get the exact same version of all tools than when the lock file was made. You should use this to install and test.

**Comment by sidkshatriya** [comment]
In the instructions we have:

> ## Create a switch to experiment with occurrences
> 
> 1. Clone this repository
> ```shell
> git clone git@github.com:voodoos/merlin-occurrences-switch.git
> ```
> 
> 2. Move to the cloned directory and run `make switch`. This should create a
>    local switch with all the necessary pin dependencies.
> 
> 3. You can then clone a project or create a new one in the same folder as the
>    `_opam` folder or in subfolders. This way opam should automatically use the
>    new local switch we just created. You will probably need to install your
>    project's dependencies in the local switch by calling `opam install .
>    --deps-only --with-test`
> 

In that case shouldn't there be a step between step 1 and step two in which we ask the user to run 

```bash
make opam.export
```

I understand that we would need to do `make opam.export` to update the lock file whenever things get updated but it needs to be run the first time by the user also...

**Comment by voodoos** [comment]
You don't need to run it since the file [already exists :-)](https://github.com/voodoos/merlin-occurrences-switch/blob/main/opam.export) It is checked-out when you clone the repository. (It should be a no-op from make since the target already exist.)

The whole idea is to ship a switch export that is known to be working. If you redo it you might fetch wip commits or desynchronised branches since the various repositories are being activelly worked on.

The instructions, as written, do what is expected on my machine. Did you actually ran them and encountered some issue ?

**Comment by sidkshatriya** [comment]
Thanks! Sorry, I was just trying to understand things. Didn't actually run it yet. Sorry for the back and forth on this ticket. At the very least I know how things are working now -- thanks for being patient :-)
